### ISSUE TITLE
Add gif example to README.md

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#20]
A good way to show to new users how to use the lib is using a gif example.

**Comment by molly7657** [comment]
I'll take this - thanks!

**Comment by victorperin** [comment]
Thankk you @molly7657 :)

**Comment by lnfnunes** [comment]
@victorperin @molly7657 
I think we can use the [(sample.jpg)](blob/master/__test__/fixture/sample.jpg) image from the tests, what do you think?

**Comment by Swayamsvk** [comment]
Can I do this?

**Comment by victorperin** [comment]
@Swayamsvk, i think @molly7657 is already doing.

@molly7657 i liked @lnfnunes idea. Can I also suggest to focus more on the terminal and make the texts bigger? this helps people viewing from mobile or in a small screen.

**Comment by molly7657** [comment]
@victorperin thanks for the feedback. I will incorporate these changes and make a PR request soon. Thanks!

**Comment by victorperin** [comment]
This was closed in #33
