### ISSUE TITLE
give transition to gif image in html

### ISSUE THREAD

**Issue by yodifm** [victorperin/qr-scanner-cli#24]

**Comment by victorperin** [comment]
Sorry @yodifm but can you desbribe it better? I couldn't understand what is the objective here.

If you describe as an user story or something like that, this could help people understand this better.

**Comment by victorperin** [comment]
I'm closing it right now, to not confuse people, but feel free to edit it. If make sense I'll reopen it.
Anyway, thank you for looking for the project :)
