### ISSUE TITLE
Update github actions to only publish when add a tag, on master branch

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#26]
Right now, the github actions is trying to publish to npm on every pull request or push created (i just used the script recommended by github itself).

I want, to build only when a new tag is pushed on master branch.

**Comment by gifcompatible** [comment]
hello, I can give this a go!

**Comment by victorperin** [comment]
Thank you @gifcompatible :)

**Comment by victorperin** [comment]
Just to document, this problem is locking #32 from working.
