### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#3]
I used an almost ready code. We need to improve the code.

**Comment by luanorlandi** [comment]
I will take that :)

**Comment by victorperin** [comment]
@luanorlandi please make the refactor easy to implement tests.

**Comment by victorperin** [comment]
@BrOrlandi and @luanorlandi sorry but I've already done a pretty good refactor.
If you guys find something to improve, I'll be glad.

**Comment by victorperin** [comment]
Closing this PR, but news are aways welcome.
