### ISSUE TITLE
Add unit tests to each function

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#30]
- [x] scanFromFile.js (#58)
- [x] infrastructure/boxen.js (#57)
- [x] infrastructure/fs.js
- [x] infrastructure/qr-reader.js (#58)
- [x] cli/index.js

Multiple people may join this issue. Please, organize and focus in a good quality pull request.

**Comment by mcvladthegoat** [comment]
Hi @victorperin ! I can do this :)

**Comment by victorperin** [comment]
Hello @mcvladthegoat are you still working on it or can we assign it to other people?

**Comment by victorperin** [comment]
This issue is resolved
