### ISSUE TITLE
Use Semantic Release on publish to NPM

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#35]
We want to use [semantic-release](https://github.com/semantic-release/semantic-release) to automatic trigger the deploy and take care of semantic versioning for us.

**Comment by aakankasha028** [comment]
Hi @victorperin. I would like to take up this issue.

**Comment by victorperin** [comment]
Thank you @aakankasha028, it is yours :)

**Comment by aakankasha028** [comment]
@victorperin I added the module and the script in package.json. Do I further need to add the tokens for git and npm?

**Comment by victorperin** [comment]
@aakankasha028 saw it just now. Don't need to worry about it.
Just show me how to add to travis. :)

**Comment by victorperin** [comment]
Closed on #45. Thanks @aakankasha028
