### ISSUE TITLE
Add option to save to clipboard

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#36]
This feature must work on Mac, Linux and Windows.

>  As an user
>  I want to copy the value of the qr to my clipboard, so
>
> Given an option `--clipboard` or `-c` and a file path (ex: `qrscanner --clipboard image.jpg`)
> When I run the program
> Then the content of the qr will be copied to my clipboard and printed to stdout

**Comment by mcvladthegoat** [comment]
@victorperin sound cool! I'll do that :) Could you assign it to me ? :)

**Comment by victorperin** [comment]
@wjbaker101 is working on it on #39

**Comment by victorperin** [comment]
@wjbaker101 thanks for the help.
@mcvladthegoat i've merged his PR, so no need to work on this anymore. Feel free to get other issues or create one new. :)
