### ISSUE TITLE
Add coverage to Travis CI and add a badge to the README

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#45]
- [] add coverage tracking to Travis CI
- [] add a coverage badge to the README.md file, with show the actual coverage.

**Comment by rlynn523** [comment]
I would like to take this if its still available

**Comment by victorperin** [comment]
It's yours @rlynn523, good luck. :)
PS: if there's any problem, write here, so others can help too.

**Comment by rlynn523** [comment]
Looks like one thing that you will need to do first is to create a Coveralls account and link it to this repo https://coveralls.io/. Once that is done, I can start implementing the necessary config updates

**Comment by victorperin** [comment]
Ok, doing that.

**Comment by victorperin** [comment]
Done, do I need to pass any info for you?

**Comment by rlynn523** [comment]
> Done, do I need to pass any info for you?

Looks like the only thing I need is the repo_token that they gave you

**Comment by rlynn523** [comment]
@victorperin Nope, that should be it!
