### ISSUE TITLE
Prepare a contributing.md file

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#46]
It's time to prepare a Contibuting.md file, because we are now with some codding patterns that need to be followed.

The file must:
- [x] Explain how the development workflow works
- [x] Show what commands we need to check before finishing a pull request.
- [x] advise about husky pre-commit flow (yet to be implemented)
- [x] Display a good code of conduct (yet to be defined)
- [x] Styleguides
  - [x] Commits Styleguide
  - [x] JavaScript Styleguide

Links that might help:
https://mozillascience.github.io/working-open-workshop/contributing/
https://github.com/atom/atom/blob/master/CONTRIBUTING.md
https://help.github.com/en/articles/setting-guidelines-for-repository-contributors
https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by victorperin** [comment]
#47 is related and important

**Comment by geovanipfranca** [comment]
**_I'm back baby._**
> Just when I thought I was out, they pull me back in.
> The Godfather: Part III, 1990
The #47 has been closed thanks @arvidboivie for your job. 👨‍💻

**Comment by yash2189** [comment]
Is this issue still open ? I might want to give a try if possible please.

**Comment by victorperin** [comment]
Closed in #46
