### ISSUE TITLE
Modify existing integration tests to count to coverage

### ISSUE THREAD

**Issue by victorperin** [victorperin/qr-scanner-cli#50]
We can't get coverage running for our integration tests. They use `execa` to execute, so it doesn't know what is being executed under the hood.

Changing this will help improve coverage (we are ate 0% haha)

**Comment by rlynn523** [comment]
I can take a look at this if it's still available

**Comment by victorperin** [comment]
It's yours.

**Comment by ozgunbal** [comment]
I also made something related to this issue, but i cannot say that it's perfect. If you're welcome, we can discuss or share ideas at the PR.

**Comment by victorperin** [comment]
@ozgunbal open a PR or put the code here, any help can serve as inspiration to other solutions too. :)

**Comment by victorperin** [comment]
@ozgunbal sent a PR, but I'm waiting for @rlynn523 to do one.

I put my considerations on what can we do to better organize those tests there.

**Comment by rlynn523** [comment]
@victorperin if @ozgunbal already has a PR submitted, I'm fine with stepping aside!

**Comment by victorperin** [comment]
@rlynn523 there's some discussion to happen, about what is the best aproach. Could be really good to include you and show what you think.

**Comment by rlynn523** [comment]
@victorperin unfortunately I've had a couple of things pop up and probably won't be able to work on this for a while.

**Comment by victorperin** [comment]
no problem @rlynn523 I think I can improve your PR from there. Thanks for your time and code. :)
