### ISSUE TITLE
Prepare a code_of_conduct.md

### ISSUE THREAD

**Issue by geovanipfranca** [victorperin/qr-scanner-cli#52]
It's time to prepare a Code of conduct for project, i'll need to create a solid Contibuting.md file creating on issue ~ #46.

The file must:

- [x] Have responsibilities in the scope
- [x] Have scope
- [x] Have standards
  - [x] Behavior
  - [x] Language
- [x] Project maintainers responsibility

Links that might help:
[Atom - Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md)
[Codamos - Code of Conduct](https://www.codamos.club/codigo-de-conduta)

**Comment by yash2189** [comment]
Can I work on the code of conduct?

**Comment by yash2189** [comment]
I have prepared the code of conduct should I make a pull request?
